// Auto-generated by CDK during deployment - DO NOT EDIT
    // Regenerated every deployment with correct API Gateway URLs
    window.API_CONFIG = {
        baseUrl: 'https://${Token[TOKEN.90]}.execute-api.eu-central-1.${Token[AWS.URLSuffix.6]}/${Token[TOKEN.98]}/',
        contactEndpoint: 'https://${Token[TOKEN.90]}.execute-api.eu-central-1.${Token[AWS.URLSuffix.6]}/${Token[TOKEN.98]}/api/v1/contact',
        businessUnit: 'construction'
    };