// Auto-generated by CDK during deployment - DO NOT EDIT
    // Regenerated every deployment with correct API Gateway URLs
    window.API_CONFIG = {
        baseUrl: 'https://${Token[TOKEN.87]}.execute-api.eu-central-1.${Token[AWS.URLSuffix.3]}/${Token[TOKEN.95]}/',
        contactEndpoint: 'https://${Token[TOKEN.87]}.execute-api.eu-central-1.${Token[AWS.URLSuffix.3]}/${Token[TOKEN.95]}/api/v1/contact',
        businessUnit: 'construction'
    };