// Auto-generated by CDK during deployment - DO NOT EDIT
    // Regenerated every deployment with correct API Gateway URLs
    window.API_CONFIG = {
        baseUrl: 'https://${Token[TOKEN.89]}.execute-api.eu-central-1.${Token[AWS.URLSuffix.5]}/${Token[TOKEN.97]}/',
        contactEndpoint: 'https://${Token[TOKEN.89]}.execute-api.eu-central-1.${Token[AWS.URLSuffix.5]}/${Token[TOKEN.97]}/api/v1/contact',
        businessUnit: 'construction'
    };